name: Reusable AI Review for Dependency Updates

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number
      ai_model:
        description: 'AI model to use for review'
        required: false
        type: string
        default: 'openai/gpt-4o'
      max_tokens:
        description: 'Maximum tokens for AI response'
        required: false
        type: number
        default: 2000
      diff_lines_limit:
        description: 'Maximum lines of diff to include in review'
        required: false
        type: number
        default: 3000
      review_language:
        description: 'Language for review output (en/ja)'
        required: false
        type: string
        default: 'en'
    secrets:
      token:
        description: 'GitHub token for API access'
        required: true

jobs:
  review:
    name: AI Review for Dependency Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      models: read

    steps:
      - name: Checkout calling repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.token }}
          fetch-depth: 0

      - name: Checkout review tool repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: korosuke613/review-dependency-pr
          path: review-tool
          fetch-depth: 1

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Get PR information
        id: pr-info
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          PR_NUMBER=${{ inputs.pr_number }}

          # Get PR details using GitHub API
          PR_DATA=$(gh pr view $PR_NUMBER --json title,body --repo ${{ github.repository }})
          PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
          PR_BODY=$(echo "$PR_DATA" | jq -r '.body // ""')

          # Get PR diff (limit to specified lines to avoid token limits)
          PR_DIFF=$(gh pr diff $PR_NUMBER --repo ${{ github.repository }} | head -${{ inputs.diff_lines_limit }})

          # Set outputs (escape newlines for GitHub Actions)
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "pr_title<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "pr_body<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "pr_diff<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run AI Review
        id: ai-review
        uses: actions/ai-inference@d645f067d89ee1d5d736a5990e327e504d1c5a4a # v1.1.0
        with:
          model: ${{ inputs.ai_model }}
          max-tokens: ${{ inputs.max_tokens }}
          prompt: |
            ${{ inputs.review_language == 'ja' && '依存関係更新PRの専門レビュアーとして、以下の変更を分析してください。

            **重要**: リポジトリ固有の具体的な分析のみを提供し、一般論は避けてください。

            分析項目:
            1. **セキュリティ影響**: 実際のCVE、既知の脆弱性修正、このリポジトリへの具体的な影響のみ記載
            2. **互換性**: 実際のAPI変更、このプロジェクトのコードに影響する変更のみ
            3. **パフォーマンス**: 実測可能な性能変化、このプロジェクトでの具体的な影響
            4. **推奨事項**: 具体的なアクション（承認/要調査/テスト必要）

            **除外する内容**:
            - 一般的なセキュリティのベストプラクティス
            - 「通常は〜」「一般的に〜」などの汎用的な説明
            - 具体的根拠のない推測

            簡潔で具体的なレビューコメントとして出力してください。' || 'As a dependency update PR specialist reviewer, analyze the following changes.

            **Important**: Provide only repository-specific concrete analysis, avoiding general statements.

            Analysis items:
            1. **Security Impact**: Only actual CVEs, known vulnerability fixes, specific impact on this repository
            2. **Compatibility**: Only actual API changes, changes affecting this projects code
            3. **Performance**: Measurable performance changes, specific impact on this project
            4. **Recommendations**: Concrete actions (approve/needs investigation/testing required)

            **Exclude**:
            - General security best practices
            - "Usually..." or "Generally..." generic explanations
            - Speculation without concrete basis

            Output as a concise and specific review comment.' }}

            PR Information:
            - Number: ${{ steps.pr-info.outputs.pr_number }}
            - Author: ${{ github.actor }}
            - Title: ${{ steps.pr-info.outputs.pr_title }}

            PR Description:
            ${{ steps.pr-info.outputs.pr_body }}

            Changes:
            ${{ steps.pr-info.outputs.pr_diff }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

      - name: Post Review Comment
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
          AI_REVIEW: ${{ steps.ai-review.outputs.response }}
        run: |
          cd review-tool
          deno run --allow-net --allow-env --allow-write src/post-review.ts
