name: Review Dependency PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number

jobs:
  get-pr-number:
    name: Get PR Number
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.event_name == 'workflow_dispatch'
    outputs:
      pr_number: ${{ steps.get-pr.outputs.pr_number }}
    steps:
      - name: Get PR number
        id: get-pr
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "pr_number=${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi

  review:
    name: AI Review for Dependency Updates
    needs: get-pr-number
    uses: ./.github/workflows/reusable-review-dependency-pr.yml
    with:
      pr_number: ${{ fromJson(needs.get-pr-number.outputs.pr_number) }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
